@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

GastroBook *-d-> "1" UniqueReservationList


'AddressBook *-right-> "1" UniqueTagList
'UniqueTagList -[hidden]down- UniqueReservationList
'UniqueTagList -[hidden]down- UniqueReservationList

'UniqueTagList -right-> "*" Tag

UniqueReservationList -d-> "*"Reservation

Reservation --> "*" Tag

Reservation --> "1" Name
Reservation --> "1" Phone
Reservation --> "1" Duration
Reservation --> "1" Identification
Reservation --> "1" Pax
Reservation --> "1" StartDate
Reservation --> "1" StartTime
Reservation -->  remark

@enduml
