@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyGastroBook" as ReadOnlyGastroBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class GastroBook
Class ModelManager
Class UserPrefs
Class PersonsList
Class PersonsListManager
Class UniqueReservationList
Class Reservation
Class Person

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

GastroBook .up.|> ReadOnlyGastroBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyGastroBook
ModelManager -left-> "1" GastroBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs
ModelManager --> "1"PersonsListManager
ModelManager --> "1"PersonsList
PersonsListManager -left->PersonsList
'change AddressBook to GastroBook
GastroBook *--> "1" UniqueReservationList
UniqueReservationList --> Reservation
PersonsList --> Person

UniqueReservationList -[hidden]right-> I


'Name -[hidden]right-> Phone
'Phone -[hidden]right-> Address'
'Address -[hidden]right-> Email



@enduml
